<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 *
 * @link       https://tropicalseo.net
 * @since      1.0.0
 *
 * @package    DashyLite 
 * @subpackage DashyLite/admin/partials
 */

//Grab all options
$options = $this->getOptionsAndRefreshToken();

// Cleanup
$site = $options['site'];

if(empty($options['site'])){
  echo('<h1>Go to settings to choose your site from Search Console</h1>');
  echo('<a href="' . admin_url( 'admin.php?page=' . $this->plugin_name ) . '-settings">' . __('Settings', $this->plugin_name) . '</a>');
  die;
}
?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://apis.google.com/js/api.js"></script>

<div id="search-console-widget">
  <div><i class="hidden dashicons dashicons-update spin" id="showSpinner"></i></div>
  <select id="searchconsole-sel-period">
    <option value="14" selected="selected">Last 14 days</option>
    <option value="30">Last 30 days</option>
    <option value="60">Last 60 days</option>
  </select>

  <div id="searchconsole-app"></div>
  <div>
    report generated by <a href="https://tropicalseo.net">TropicalSeo</a>
  </div>

</div>
<script>

// global variables
var access_token = "<?php echo($options['token']['access_token']) ?>";
var site = "<?php echo($site) ?>";
var data,chart;
var period = jQuery('select[id=searchconsole-sel-period]').val();

jQuery('select[id=searchconsole-sel-period]').change(function(){
  period= jQuery(this).val();
  getReport();
});

google.charts.load('current', {'packages':['corechart']});

var chartOptions={width:"100%",height:400,focusTarget:"category",chartArea:{width:"94%"},hAxis:{showTextEvery:4},vAxes:{0:{direction:-1,maxValue:1,textPosition:"none"},1:{textPosition:"none"},2:{textPosition:"none"},3:{textPosition:"none"}},series:{0:{type:"line",targetAxisIndex:1,tooltip:!0},1:{type:"line",targetAxisIndex:2,tooltip:!0},2:{type:"line",targetAxisIndex:3,tooltip:!0},3:{type:"line",targetAxisIndex:0,tooltip:!0},4:{type:"line",targetAxisIndex:0,tooltip:!0}}};function formatData(t){var e=new google.visualization.DataTable;return e.addColumn("date","Keys"),e.addColumn("number","Clicks"),e.addColumn("number","Impressions"),e.addColumn("number","CTR"),e.addColumn("number","Position"),_.forEach(t,function(t){e.addRow([new Date(t.keys[0]),t.clicks,t.impressions,100*t.ctr,parseFloat(t.position)])}),e}function selectHandler(){if(chart.getSelection()[0].column){var t=chart.getSelection()[0].column-1;chartOptions.series[t].tooltip=!chartOptions.series[t].tooltip,0==chartOptions.series[t].lineWidth?(chartOptions.series[t].lineWidth=2,chartOptions.series[t].areaOpacity=.3):(chartOptions.series[t].lineWidth=0,chartOptions.series[t].areaOpacity=0),chart.draw(data,chartOptions)}}function getReport(){gapi.client.webmasters.searchanalytics.query({siteUrl:site,rowLimit:null,searchType:"web",startDate:moment().subtract(period,"days").format("YYYY-MM-DD"),endDate:moment().format("YYYY-MM-DD"),dimensions:["date"]}).then(function(t){data=formatData(t.result.rows),chart=new google.visualization.LineChart(document.getElementById("searchconsole-app")),chart.draw(data,chartOptions),google.visualization.events.addListener(chart,"select",selectHandler)}).then(null,function(t){console.log(t)})}!function(t){"use strict";access_token&&gapi.load("client",function(){t("#showSpinner").toggleClass("hidden"),gapi.client.load("webmasters","v3").then(function(){gapi.auth.setToken({access_token:access_token}),getReport(),t("#showSpinner").toggleClass("hidden")})})}(jQuery);
</script>
<style type="text/css">
.dashicons.spin {
   animation: dashicons-spin 1s infinite;
   animation-timing-function: linear;
}

@keyframes dashicons-spin {
   0% {
      transform: rotate( 0deg );
   }
   100% {
      transform: rotate( 360deg );
   }
}   
</style>